/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.AlumnosMetodos;
import controlador.BBDD;
import controlador.PracticaMetodos;
import elementos.Notification;
import elementos.mensaje.message.MessageDialog;
import java.awt.Color;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import jnafilechooser.api.JnaFileChooser;
import modelo.Alumno;
import modelo.Practica;
import sun.misc.IOUtils;
import static vista.PanelAlumnos.tfBusqueda;

/**
 *
 * @author LinkA
 */
public class VentanaAgregarPractica extends javax.swing.JFrame {

    BBDD bbdd = new BBDD();
    PracticaMetodos practicaMetodos = new PracticaMetodos();
    FileInputStream cvASubir1;
    FileInputStream cvASubir2;
    Practica practica;
    Color botonSeleccionado = new Color(230, 161, 2);
    Color botonNoSeleccionado = new Color(254, 177, 3);
    /**
     * Creates new form VentanaMasInfoAlumno
     */
    public VentanaAgregarPractica() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        tfIdConvenio = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        botonAnexo8 = new javax.swing.JLabel();
        tfanexo4 = new javax.swing.JLabel();
        botonAnexo4 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        tfAnexo8 = new javax.swing.JLabel();
        tfIdAluno = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/add_profile_img.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel2.setText("Id Alumno");

        jLabel4.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel4.setText("Id Convenio");

        tfIdConvenio.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        tfIdConvenio.setForeground(new java.awt.Color(204, 204, 204));
        tfIdConvenio.setText("id convenio");
        tfIdConvenio.setBorder(null);
        tfIdConvenio.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfIdConvenioFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfIdConvenioFocusLost(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel3.setText("Agregar nuevo alumno");

        jLabel14.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel14.setText("Anexo8");

        jPanel5.setBackground(new java.awt.Color(254, 177, 3));
        jPanel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel5MouseExited(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel9.setText("Aceptar");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(32, 32, 32))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(14, 14, 14))
        );

        botonAnexo8.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        botonAnexo8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/subir (Personalizado).png"))); // NOI18N
        botonAnexo8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonAnexo8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonAnexo8MouseClicked(evt);
            }
        });

        tfanexo4.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        tfanexo4.setText("Subir Anexo4");

        botonAnexo4.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        botonAnexo4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/subir (Personalizado).png"))); // NOI18N
        botonAnexo4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonAnexo4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonAnexo4MouseClicked(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel16.setText("Anexo4");

        tfAnexo8.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        tfAnexo8.setText("Subir Anexo8");

        tfIdAluno.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        tfIdAluno.setForeground(new java.awt.Color(204, 204, 204));
        tfIdAluno.setText("id alumno");
        tfIdAluno.setBorder(null);
        tfIdAluno.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfIdAlunoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfIdAlunoFocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(142, 142, 142)
                                .addComponent(jLabel3))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(192, 192, 192)
                                .addComponent(jLabel1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(botonAnexo4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tfanexo4)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(9, 9, 9)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tfIdAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel2))))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tfIdConvenio, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel4))
                                        .addGap(28, 28, 28))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel14)
                                            .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(botonAnexo8)
                                                .addGap(18, 18, 18)
                                                .addComponent(tfAnexo8)))
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(20, 20, 20)
                    .addComponent(jLabel16)
                    .addContainerGap(448, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(13, 13, 13)
                        .addComponent(tfIdAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(tfIdConvenio, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(115, 115, 115)
                                .addComponent(tfanexo4))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(105, 105, 105)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(botonAnexo8)
                                    .addComponent(botonAnexo4))))
                        .addGap(226, 226, 226)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(jLabel14)
                        .addGap(45, 45, 45)
                        .addComponent(tfAnexo8)))
                .addContainerGap(72, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(357, 357, 357)
                    .addComponent(jLabel16)
                    .addContainerGap(381, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botonAnexo8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAnexo8MouseClicked
            JnaFileChooser fileChooser = new JnaFileChooser();
            fileChooser.setMode(JnaFileChooser.Mode.Files);
            fileChooser.showOpenDialog(this);
            File cvSubido = fileChooser.getSelectedFile();
            if (cvSubido != null) {
                try {
                    FileInputStream fis = new FileInputStream(cvSubido);
                    cvASubir1 = fis;
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(VentanaAgregarPractica.class.getName()).log(Level.SEVERE, null, ex);
                }
                Notification notificacion = new Notification(this, Notification.Type.SUCCESS, Notification.Location.TOP_CENTER, "Anexo8 preparado para agregar");
                notificacion.showNotification();
            }else{
                Notification notificacion = new Notification(this, Notification.Type.INFO, Notification.Location.TOP_CENTER, "La subida del Anexo8 ha sido cancelada");
                notificacion.showNotification();
            }
        
    }//GEN-LAST:event_botonAnexo8MouseClicked

    private void jPanel5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseEntered
        jPanel5.setBackground(botonSeleccionado);
    }//GEN-LAST:event_jPanel5MouseEntered

    private void jPanel5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseExited
        jPanel5.setBackground(botonNoSeleccionado);
    }//GEN-LAST:event_jPanel5MouseExited

    private void jPanel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseClicked
        practicaMetodos.comprobarCampos(this, tfIdConvenio.getText(), tfIdAluno.getText(), cvASubir1, cvASubir2);
    }//GEN-LAST:event_jPanel5MouseClicked

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        if (!tfBusqueda.getText().equals("Busque en cualquier campo")) {
            List<Practica> practica = practicaMetodos.rellenarListaPractica("SELECT * FROM practica WHERE CAST(id AS TEXT) LIKE '%" + tfBusqueda.getText()
                + "%' "
                + "OR id_alumno LIKE '%" + tfBusqueda.getText() + "%' "
                + "OR fecha_inicio LIKE '%" + tfBusqueda.getText() + "%' "
                + "OR fecha_fin LIKE '%" + tfBusqueda.getText() + "%' "
                + "OR id_convenio LIKE '%" + tfBusqueda.getText() + "%' ORDER BY id ASC");
            PanelPractica.tablaPractica = practicaMetodos.rellenarTablaPractica(PanelPractica.tablaPractica, practica);
        }else{
            List<Practica> practicas = practicaMetodos.rellenarListaPractica("SELECT * FROM practica where eliminado = FALSE;");
            PanelPractica.tablaPractica = practicaMetodos.rellenarTablaPractica(PanelPractica.tablaPractica, practicas);
        }
    }//GEN-LAST:event_formWindowClosed

    private void botonAnexo4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAnexo4MouseClicked
        JnaFileChooser fileChooser = new JnaFileChooser();
            fileChooser.setMode(JnaFileChooser.Mode.Files);
            fileChooser.showOpenDialog(this);
            File cvSubido = fileChooser.getSelectedFile();
            if (cvSubido != null) {
                try {
                    FileInputStream fis = new FileInputStream(cvSubido);
                    cvASubir2 = fis;
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(VentanaAgregarPractica.class.getName()).log(Level.SEVERE, null, ex);
                }
                Notification notificacion = new Notification(this, Notification.Type.SUCCESS, Notification.Location.TOP_CENTER, "Anexo4 preparado para agregar");
                notificacion.showNotification();
            }else{
                Notification notificacion = new Notification(this, Notification.Type.INFO, Notification.Location.TOP_CENTER, "La subida del Anexo4 ha sido cancelada");
                notificacion.showNotification();
            }
    }//GEN-LAST:event_botonAnexo4MouseClicked

    private void tfIdConvenioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfIdConvenioFocusLost
        if (tfIdConvenio.getText().isEmpty()) {
            tfIdConvenio.setText("id convenio");
            tfIdConvenio.setForeground(new Color(204, 204, 204));
        }
    }//GEN-LAST:event_tfIdConvenioFocusLost

    private void tfIdConvenioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfIdConvenioFocusGained
        if (tfIdConvenio.getText().equals("id convenio")) {
            tfIdConvenio.setText("");
            tfIdConvenio.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_tfIdConvenioFocusGained

    private void tfIdAlunoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfIdAlunoFocusGained
        if (tfIdAluno.getText().equals("id alumno")) {
            tfIdAluno.setText("");
            tfIdAluno.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_tfIdAlunoFocusGained

    private void tfIdAlunoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfIdAlunoFocusLost
        if (tfIdAluno.getText().isEmpty()) {
            tfIdAluno.setText("id alumno");
            tfIdAluno.setForeground(new Color(204, 204, 204));
        }
    }//GEN-LAST:event_tfIdAlunoFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel botonAnexo4;
    private javax.swing.JLabel botonAnexo8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel tfAnexo8;
    private javax.swing.JTextField tfIdAluno;
    private javax.swing.JTextField tfIdConvenio;
    private javax.swing.JLabel tfanexo4;
    // End of variables declaration//GEN-END:variables
}
