/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.AlumnosMetodos;
import controlador.AnexoMetodos;
import controlador.BBDD;
import elementos.Notification;
import elementos.mensaje.message.MessageDialog;
import java.awt.Color;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import jnafilechooser.api.JnaFileChooser;
import modelo.Alumno;
import modelo.Anexo22;
import sun.misc.IOUtils;
import static vista.PanelAlumnos.tfBusqueda;

/**
 *
 * @author LinkA
 */
public class VentanaAgregarAnexo extends javax.swing.JFrame {

    BBDD bbdd = new BBDD();
    AnexoMetodos anexoMetodos = new AnexoMetodos();
    FileInputStream cvASubir;
    Anexo22 anexo;
    Color botonSeleccionado = new Color(230, 161, 2);
    Color botonNoSeleccionado = new Color(254, 177, 3);
    /**
     * Creates new form VentanaMasInfoAlumno
     */
    public VentanaAgregarAnexo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tfIdCentro = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        tfFamiliaProfesional = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        tfCicloFormativo = new javax.swing.JTextField();
        jSeparator10 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/IconoAgregarAnexo.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel2.setText("ID del Centro");

        tfIdCentro.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        tfIdCentro.setForeground(new java.awt.Color(204, 204, 204));
        tfIdCentro.setText("Id del centro");
        tfIdCentro.setBorder(null);
        tfIdCentro.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfIdCentroFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfIdCentroFocusLost(evt);
            }
        });
        tfIdCentro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfIdCentroActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel4.setText("Familia Profesional");

        tfFamiliaProfesional.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        tfFamiliaProfesional.setForeground(new java.awt.Color(204, 204, 204));
        tfFamiliaProfesional.setText("Familia Profesional");
        tfFamiliaProfesional.setBorder(null);
        tfFamiliaProfesional.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfFamiliaProfesionalFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfFamiliaProfesionalFocusLost(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel11.setText("Ciclo Formativo");

        tfCicloFormativo.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        tfCicloFormativo.setForeground(new java.awt.Color(204, 204, 204));
        tfCicloFormativo.setText("Ciclo Formativo");
        tfCicloFormativo.setBorder(null);
        tfCicloFormativo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfCicloFormativoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfCicloFormativoFocusLost(evt);
            }
        });
        tfCicloFormativo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCicloFormativoActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel3.setText("Agregar nuevo Anexo");

        jLabel14.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel14.setText("Anexo2.2");

        jPanel5.setBackground(new java.awt.Color(254, 177, 3));
        jPanel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel5MouseExited(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel9.setText("Aceptar");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(32, 32, 32))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(14, 14, 14))
        );

        jLabel7.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/subir (Personalizado).png"))); // NOI18N
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel5.setText("  Subir un Anexo2.2");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(192, 192, 192)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(146, 146, 146))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(158, 158, 158))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 194, Short.MAX_VALUE)
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(0, 424, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfIdCentro, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addGap(28, 28, 28))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel11)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfFamiliaProfesional, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(28, 28, 28))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(tfCicloFormativo, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(104, 104, 104)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfFamiliaProfesional, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfIdCentro, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addComponent(tfCicloFormativo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(jLabel7))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(jLabel5)))))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
            JnaFileChooser fileChooser = new JnaFileChooser();
            fileChooser.setMode(JnaFileChooser.Mode.Files);
            fileChooser.showOpenDialog(this);
            File cvSubido = fileChooser.getSelectedFile();
            if (cvSubido != null) {
                try {
                    FileInputStream fis = new FileInputStream(cvSubido);
                    cvASubir = fis;
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(VentanaAgregarAnexo.class.getName()).log(Level.SEVERE, null, ex);
                }
                Notification notificacion = new Notification(this, Notification.Type.SUCCESS, Notification.Location.TOP_CENTER, "Curriculum preparado para agregar");
                notificacion.showNotification();
            }else{
                Notification notificacion = new Notification(this, Notification.Type.INFO, Notification.Location.TOP_CENTER, "La subida de curriculum ha sido cancelada");
                notificacion.showNotification();
            }
        
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jPanel5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseEntered
        jPanel5.setBackground(botonSeleccionado);
    }//GEN-LAST:event_jPanel5MouseEntered

    private void jPanel5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseExited
        jPanel5.setBackground(botonNoSeleccionado);
    }//GEN-LAST:event_jPanel5MouseExited

    private void jPanel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseClicked
        anexoMetodos.comprobarCampos(this, tfIdCentro.getText(), tfFamiliaProfesional.getText(), tfCicloFormativo.getText(), cvASubir);
    }//GEN-LAST:event_jPanel5MouseClicked

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        if (!tfBusqueda.getText().equals("Busque en cualquier campo")) {
            List<Anexo22> anexo = anexoMetodos.rellenarListaAnexo("SELECT * FROM anexo22 WHERE CAST(id AS TEXT) LIKE '%" + tfBusqueda.getText()
                + "%' "
                + "OR idCentro LIKE '%" + tfBusqueda.getText() + "%' "
                + "OR familia_profesional LIKE '%" + tfBusqueda.getText() + "%' "
                + "OR ciclo LIKE '%" + tfBusqueda.getText() + "%' ORDER BY id ASC");
            PanelAnexo22.tablaAnexos = anexoMetodos.rellenarTablaAnexo(PanelAnexo22.tablaAnexos, anexo);
        }else{
            List<Anexo22> anexos = anexoMetodos.rellenarListaAnexo("SELECT * FROM anexo22 where eliminado = FALSE;");
            PanelAnexo22.tablaAnexos = anexoMetodos.rellenarTablaAnexo(PanelAnexo22.tablaAnexos, anexos);
        }
    }//GEN-LAST:event_formWindowClosed

    private void tfCicloFormativoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfCicloFormativoFocusLost
        if (tfCicloFormativo.getText().isEmpty()) {
            tfCicloFormativo.setText("Ciclo Formativo");
            tfCicloFormativo.setForeground(new Color(204, 204, 204));
        }
    }//GEN-LAST:event_tfCicloFormativoFocusLost

    private void tfCicloFormativoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfCicloFormativoFocusGained
        if (tfCicloFormativo.getText().equals("Ciclo Formativo")) {
            tfCicloFormativo.setText("");
            tfCicloFormativo.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_tfCicloFormativoFocusGained

    private void tfCicloFormativoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCicloFormativoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCicloFormativoActionPerformed

    private void tfFamiliaProfesionalFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfFamiliaProfesionalFocusLost
        if (tfFamiliaProfesional.getText().isEmpty()) {
            tfFamiliaProfesional.setText("Famila Profesional");
            tfFamiliaProfesional.setForeground(new Color(204, 204, 204));
        }
    }//GEN-LAST:event_tfFamiliaProfesionalFocusLost

    private void tfFamiliaProfesionalFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfFamiliaProfesionalFocusGained
        if (tfFamiliaProfesional.getText().equals("Familia Profesional")) {
            tfFamiliaProfesional.setText("");
            tfFamiliaProfesional.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_tfFamiliaProfesionalFocusGained
    private void tfFamiliaProfesionalActionPerformed(java.awt.event.ActionEvent evt) {                                                 
           // TODO add your handling code here:
       }
    private void tfIdCentroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfIdCentroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfIdCentroActionPerformed

    private void tfIdCentroFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfIdCentroFocusLost
        if (tfIdCentro.getText().isEmpty()) {
            tfIdCentro.setText("Id del centro");
            tfIdCentro.setForeground(new Color(204, 204, 204));
        }
    }//GEN-LAST:event_tfIdCentroFocusLost

    private void tfIdCentroFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfIdCentroFocusGained
        if (tfIdCentro.getText().equals("Id del centro")) {
            tfIdCentro.setText("");
            tfIdCentro.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_tfIdCentroFocusGained
                                          
                                             


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextField tfCicloFormativo;
    private javax.swing.JTextField tfFamiliaProfesional;
    private javax.swing.JTextField tfIdCentro;
    // End of variables declaration//GEN-END:variables
}
