/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;


import controlador.BBDD;
import controlador.EmpresaMetodos;
import elementos.Notification;
import elementos.mensaje.message.MessageDialog;
import java.awt.Color;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import jnafilechooser.api.JnaFileChooser;
import modelo.Empresa;
import sun.misc.IOUtils;
import static vista.PanelEmpresa.tablaEmpresa;
import static vista.PanelEmpresa.tfBusqueda;

/**
 *
 * @author LinkA
 */
public class VentanaMasInfoEmpresa extends javax.swing.JFrame {

    BBDD bbdd = new BBDD();
    EmpresaMetodos empresaMetodos = new EmpresaMetodos();

    //byte[] cvActual;
    //FileInputStream cvASubir;
    Empresa empresa;
    int idEmpresa;
    Color botonSeleccionado = new Color(230, 161, 2);
    Color botonNoSeleccionado = new Color(254, 177, 3);

    /**
     * Creates new form VentanaMasInfoAlumno
     */
    public VentanaMasInfoEmpresa() {
        initComponents();
        empresa = bbdd.obtenerEmpresa(empresaMetodos.idEscogido);
        idEmpresa = empresa.getId();
        rellenarCampos(empresa);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTelefonoContacto1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabelNombre = new javax.swing.JLabel();
        tfNombre = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabelCif = new javax.swing.JLabel();
        tfCif = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jLabelAmbito = new javax.swing.JLabel();
        tfAmbito = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        jLabelTelefono = new javax.swing.JLabel();
        tftelefono = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        jLabelDuenio = new javax.swing.JLabel();
        tfDuenio = new javax.swing.JTextField();
        jSeparator9 = new javax.swing.JSeparator();
        jLabelDireccion = new javax.swing.JLabel();
        tfDireccion = new javax.swing.JTextField();
        jSeparator10 = new javax.swing.JSeparator();
        jLabelTutor = new javax.swing.JLabel();
        tfTutor = new javax.swing.JTextField();
        jSeparator11 = new javax.swing.JSeparator();
        jLabelTelefonoContacto = new javax.swing.JLabel();
        tfTelefonoContacto = new javax.swing.JTextField();
        jSeparator12 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabelEmail = new javax.swing.JLabel();
        jLabelNombreContacto = new javax.swing.JLabel();
        tfNombreContacto = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabelEmailContacto = new javax.swing.JLabel();
        tfEmailContacto = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        tfEmail = new javax.swing.JTextField();

        jLabelTelefonoContacto1.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabelTelefonoContacto1.setText("Telefóno de contacto");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/profile_img (Personalizado).png"))); // NOI18N

        jLabelNombre.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabelNombre.setText("Nombre");

        tfNombre.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        tfNombre.setText("Nombre de la empresa");
        tfNombre.setBorder(null);
        tfNombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfNombreFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfNombreFocusLost(evt);
            }
        });

        jLabelCif.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabelCif.setText("Cif");

        tfCif.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        tfCif.setText("Cif");
        tfCif.setBorder(null);
        tfCif.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfCifFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfCifFocusLost(evt);
            }
        });

        jLabelAmbito.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabelAmbito.setText("Ambito");

        tfAmbito.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        tfAmbito.setText("Ambito");
        tfAmbito.setBorder(null);
        tfAmbito.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfAmbitoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfAmbitoFocusLost(evt);
            }
        });
        tfAmbito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfAmbitoActionPerformed(evt);
            }
        });

        jLabelTelefono.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabelTelefono.setText("Telefóno");

        tftelefono.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        tftelefono.setText("Telefóno");
        tftelefono.setBorder(null);
        tftelefono.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tftelefonoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tftelefonoFocusLost(evt);
            }
        });

        jLabelDuenio.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabelDuenio.setText("Dueño");

        tfDuenio.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        tfDuenio.setText("Dueño de la empresa");
        tfDuenio.setBorder(null);
        tfDuenio.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfDuenioFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfDuenioFocusLost(evt);
            }
        });

        jLabelDireccion.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabelDireccion.setText("Dirección");

        tfDireccion.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        tfDireccion.setText("Dirección");
        tfDireccion.setBorder(null);
        tfDireccion.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfDireccionFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfDireccionFocusLost(evt);
            }
        });

        jLabelTutor.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabelTutor.setText("Tutor");

        tfTutor.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        tfTutor.setText("Tutor");
        tfTutor.setBorder(null);
        tfTutor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfTutorFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfTutorFocusLost(evt);
            }
        });

        jLabelTelefonoContacto.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabelTelefonoContacto.setText("Telefóno de contacto");

        tfTelefonoContacto.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        tfTelefonoContacto.setText("Telefóno de contacto");
        tfTelefonoContacto.setBorder(null);
        tfTelefonoContacto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfTelefonoContactoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfTelefonoContactoFocusLost(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel3.setText("Información de la empresa");

        jPanel5.setBackground(new java.awt.Color(254, 177, 3));
        jPanel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel5MouseExited(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel9.setText("Aceptar");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(32, 32, 32))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(14, 14, 14))
        );

        jLabelEmail.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabelEmail.setText("Email");

        jLabelNombreContacto.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabelNombreContacto.setText("Nombre de contacto");

        tfNombreContacto.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        tfNombreContacto.setText("Nombre de contacto");
        tfNombreContacto.setBorder(null);
        tfNombreContacto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfNombreContactoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfNombreContactoFocusLost(evt);
            }
        });

        jLabelEmailContacto.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabelEmailContacto.setText("Email de contacto");

        tfEmailContacto.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        tfEmailContacto.setText("Email de contacto");
        tfEmailContacto.setBorder(null);
        tfEmailContacto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfEmailContactoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfEmailContactoFocusLost(evt);
            }
        });

        tfEmail.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        tfEmail.setText("Email");
        tfEmail.setBorder(null);
        tfEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfEmailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfEmailFocusLost(evt);
            }
        });
        tfEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfEmailActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addComponent(jLabel3)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSeparator12, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(9, 9, 9)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tfAmbito, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabelAmbito)
                                            .addComponent(jLabelEmail)
                                            .addComponent(tfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(9, 9, 9)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(tftelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabelTelefono)))
                                        .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jSeparator11, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(9, 9, 9)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(tfTutor, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabelTutor)))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(10, 10, 10)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(tfNombreContacto, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabelNombreContacto)
                                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(9, 9, 9)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabelNombre)
                                            .addComponent(tfDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabelDireccion))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(9, 9, 9)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(tfCif, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabelCif)))
                                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(9, 9, 9)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(tfDuenio, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabelDuenio)))
                                        .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(186, 186, 186))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfEmailContacto, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelTelefonoContacto)
                    .addComponent(tfTelefonoContacto, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelEmailContacto))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelCif)
                        .addGap(18, 18, 18)
                        .addComponent(tfCif, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(jLabelDuenio)
                        .addGap(18, 18, 18)
                        .addComponent(tfDuenio, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelNombre)
                        .addGap(18, 18, 18)
                        .addComponent(tfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(jLabelDireccion)
                        .addGap(18, 18, 18)
                        .addComponent(tfDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelAmbito)
                        .addGap(18, 18, 18)
                        .addComponent(tfAmbito, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelEmail)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator12, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelTelefono)
                        .addGap(18, 18, 18)
                        .addComponent(tftelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelTutor)
                        .addGap(18, 18, 18)
                        .addComponent(tfTutor, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator11, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelNombreContacto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfNombreContacto, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelTelefonoContacto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfTelefonoContacto, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelEmailContacto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(tfEmailContacto, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tfNombreFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfNombreFocusGained
        if (tfNombre.getText().equals("Nombre del alumno")) {
            tfNombre.setText("");
            tfNombre.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_tfNombreFocusGained

    private void tfNombreFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfNombreFocusLost
        if (tfNombre.getText().isEmpty()) {
            tfNombre.setText("Nombre del alumno");
            tfNombre.setForeground(new Color(204, 204, 204));
        }
    }//GEN-LAST:event_tfNombreFocusLost

    private void tfCifFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfCifFocusGained
        if (tfCif.getText().equals("Apellidos")) {
            tfCif.setText("");
            tfCif.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_tfCifFocusGained

    private void tfCifFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfCifFocusLost
        if (tfCif.getText().isEmpty()) {
            tfCif.setText("Apellidos");
            tfCif.setForeground(new Color(204, 204, 204));
        }
    }//GEN-LAST:event_tfCifFocusLost

    private void tfDireccionFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfDireccionFocusGained
        if (tfDireccion.getText().equals("Dni")) {
            tfDireccion.setText("");
            tfDireccion.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_tfDireccionFocusGained

    private void tfDireccionFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfDireccionFocusLost
        if (tfDireccion.getText().isEmpty()) {
            tfDireccion.setText("Dni");
            tfDireccion.setForeground(new Color(204, 204, 204));
        }
    }//GEN-LAST:event_tfDireccionFocusLost

    private void tfDuenioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfDuenioFocusGained
        if (tfDuenio.getText().equals("Dirección")) {
            tfDuenio.setText("");
            tfDuenio.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_tfDuenioFocusGained

    private void tfDuenioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfDuenioFocusLost
        if (tfDuenio.getText().isEmpty()) {
            tfDuenio.setText("Dirección");
            tfDuenio.setForeground(new Color(204, 204, 204));
        }
    }//GEN-LAST:event_tfDuenioFocusLost

    private void tfAmbitoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfAmbitoFocusGained
        if (tfAmbito.getText().equals("Correo electrónico")) {
            tfAmbito.setText("");
            tfAmbito.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_tfAmbitoFocusGained

    private void tfAmbitoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfAmbitoFocusLost
        if (tfAmbito.getText().isEmpty()) {
            tfAmbito.setText("Correo electrónico");
            tfAmbito.setForeground(new Color(204, 204, 204));
        }
    }//GEN-LAST:event_tfAmbitoFocusLost

    private void tftelefonoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tftelefonoFocusGained
        if (tftelefono.getText().equals("Número de Seguridad Social")) {
            tftelefono.setText("");
            tftelefono.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_tftelefonoFocusGained

    private void tftelefonoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tftelefonoFocusLost
        if (tftelefono.getText().isEmpty()) {
            tftelefono.setText("Número de Seguridad Social");
            tftelefono.setForeground(new Color(204, 204, 204));
        }
    }//GEN-LAST:event_tftelefonoFocusLost

    private void tfTelefonoContactoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfTelefonoContactoFocusGained
        if (tfTelefonoContacto.getText().equals("Teléfono")) {
            tfTelefonoContacto.setText("");
            tfTelefonoContacto.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_tfTelefonoContactoFocusGained

    private void tfTelefonoContactoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfTelefonoContactoFocusLost
        if (tfTelefonoContacto.getText().isEmpty()) {
            tfTelefonoContacto.setText("Teléfono");
            tfTelefonoContacto.setForeground(new Color(204, 204, 204));
        }
    }//GEN-LAST:event_tfTelefonoContactoFocusLost

    private void tfTutorFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfTutorFocusGained
        if (tfTutor.getText().equals("Ciclo")) {
            tfTutor.setText("");
            tfTutor.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_tfTutorFocusGained

    private void tfTutorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfTutorFocusLost
        if (tfTutor.getText().isEmpty()) {
            tfTutor.setText("Ciclo");
            tfTutor.setForeground(new Color(204, 204, 204));
        }
    }//GEN-LAST:event_tfTutorFocusLost

    private void jPanel5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseEntered
        jPanel5.setBackground(botonSeleccionado);
    }//GEN-LAST:event_jPanel5MouseEntered

    private void jPanel5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseExited
        jPanel5.setBackground(botonNoSeleccionado);
    }//GEN-LAST:event_jPanel5MouseExited

    private void jPanel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseClicked
        

    }//GEN-LAST:event_jPanel5MouseClicked

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        if (!tfBusqueda.getText().equals("Busque en cualquier campo")) {
            List<Empresa> empresas = empresaMetodos.rellenarListaEmpresa("SELECT * FROM empresa WHERE CAST(id AS TEXT) LIKE '%" + tfBusqueda.getText()
                    + "%' "
                    + "OR nombre LIKE '%" + tfBusqueda.getText() + "%' "
                    + "OR cif LIKE '%" + tfBusqueda.getText() + "%' "
                    + "OR direccion LIKE '%" + tfBusqueda.getText() + "%' "
                    + "OR dueño LIKE '%" + tfBusqueda.getText() + "%' "
                    + "OR ambito LIKE '%" + tfBusqueda.getText() + "%' "
                    + "OR telefono LIKE '%" + tfBusqueda.getText() + "%' "
                    + "OR email LIKE '%" + tfBusqueda.getText() + "%' "        
                    + "OR tutor LIKE '%" + tfBusqueda.getText() + "%' "
                    + "OR telefono_contacto LIKE '%" + tfBusqueda.getText() + "%' "        
                    + "OR nombre_contacto LIKE '%" + tfBusqueda.getText() + "%' "
                    + "OR email_contacto LIKE '%" + tfBusqueda.getText() + "%' ORDER BY id ASC");
            PanelEmpresa.tablaEmpresa = empresaMetodos.rellenarTablaEmpresa(tablaEmpresa, empresas);
        }
    }//GEN-LAST:event_formWindowClosed

    private void tfAmbitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfAmbitoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfAmbitoActionPerformed

    private void tfNombreContactoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfNombreContactoFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNombreContactoFocusGained

    private void tfNombreContactoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfNombreContactoFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNombreContactoFocusLost

    private void tfEmailContactoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfEmailContactoFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_tfEmailContactoFocusGained

    private void tfEmailContactoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfEmailContactoFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_tfEmailContactoFocusLost

    private void tfEmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfEmailFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_tfEmailFocusGained

    private void tfEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfEmailFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_tfEmailFocusLost

    private void tfEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfEmailActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelAmbito;
    private javax.swing.JLabel jLabelCif;
    private javax.swing.JLabel jLabelDireccion;
    private javax.swing.JLabel jLabelDuenio;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelEmailContacto;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelNombreContacto;
    private javax.swing.JLabel jLabelTelefono;
    private javax.swing.JLabel jLabelTelefonoContacto;
    private javax.swing.JLabel jLabelTelefonoContacto1;
    private javax.swing.JLabel jLabelTutor;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTextField tfAmbito;
    private javax.swing.JTextField tfCif;
    private javax.swing.JTextField tfDireccion;
    private javax.swing.JTextField tfDuenio;
    private javax.swing.JTextField tfEmail;
    private javax.swing.JTextField tfEmailContacto;
    private javax.swing.JTextField tfNombre;
    private javax.swing.JTextField tfNombreContacto;
    private javax.swing.JTextField tfTelefonoContacto;
    private javax.swing.JTextField tfTutor;
    private javax.swing.JTextField tftelefono;
    // End of variables declaration//GEN-END:variables

    private void rellenarCampos(Empresa empresa) {
        tfNombre.setText(empresa.getNombre());
        tfCif.setText(empresa.getCif());
        tfDireccion.setText(empresa.getDireccion());
        tfDuenio.setText(empresa.getDuenio());
        tfAmbito.setText(empresa.getAmbito());
        tftelefono.setText(empresa.getTelefono());
        tfEmail.setText(empresa.getEmail());
        tfTutor.setText(empresa.getTutor());
        tfTelefonoContacto.setText(empresa.getTelefono_contacto());
        tfNombreContacto.setText(empresa.getNombre_contacto());
        tfEmailContacto.setText(empresa.getEmail_contacto());
       
    }
}
