/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;


import controlador.BBDD;
import controlador.EmpresaMetodos;
import elementos.Notification;
import elementos.mensaje.message.MessageDialog;
import java.awt.Color;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import jnafilechooser.api.JnaFileChooser;

import modelo.Empresa;
import sun.misc.IOUtils;
import static vista.PanelEmpresa.tfBusqueda;


/**
 *
 * @author LinkA
 */
public class VentanaAgregarEmpresa extends javax.swing.JFrame {

    BBDD bbdd = new BBDD();
    EmpresaMetodos empresaMetodos = new EmpresaMetodos();
    Empresa empresa;
    Color botonSeleccionado = new Color(230, 161, 2);
    Color botonNoSeleccionado = new Color(254, 177, 3);

    /**
     * Creates new form VentanaMasInfoAlumno
     */
    public VentanaAgregarEmpresa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator15 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabelNombre = new javax.swing.JLabel();
        tfNombreDeLaEmpresa = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabelCif = new javax.swing.JLabel();
        tfCif = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jLabelAmbito = new javax.swing.JLabel();
        tfAmbito = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        jLabelTelefono = new javax.swing.JLabel();
        tfTelefono = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        jLabelDueño = new javax.swing.JLabel();
        tfDueño = new javax.swing.JTextField();
        jSeparator9 = new javax.swing.JSeparator();
        jLabelDirección = new javax.swing.JLabel();
        tfDireccion = new javax.swing.JTextField();
        jSeparator10 = new javax.swing.JSeparator();
        jLabelTutor = new javax.swing.JLabel();
        tfTutor = new javax.swing.JTextField();
        jSeparator11 = new javax.swing.JSeparator();
        jLabelEmail = new javax.swing.JLabel();
        tfEmail = new javax.swing.JTextField();
        jSeparator12 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabelEmail1 = new javax.swing.JLabel();
        tfEmailDeContacto = new javax.swing.JTextField();
        jSeparator13 = new javax.swing.JSeparator();
        jLabelNombreDeContacto = new javax.swing.JLabel();
        tfNombreDeContacto = new javax.swing.JTextField();
        jSeparator14 = new javax.swing.JSeparator();
        jLabelEmailDelContacto = new javax.swing.JLabel();
        tfTelefonoDeContacto1 = new javax.swing.JTextField();
        jSeparator16 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/add_profile_img.png"))); // NOI18N

        jLabelNombre.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabelNombre.setText("Nombre");

        tfNombreDeLaEmpresa.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        tfNombreDeLaEmpresa.setForeground(new java.awt.Color(204, 204, 204));
        tfNombreDeLaEmpresa.setText("Nombre de la empresa");
        tfNombreDeLaEmpresa.setBorder(null);
        tfNombreDeLaEmpresa.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfNombreDeLaEmpresaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfNombreDeLaEmpresaFocusLost(evt);
            }
        });
        tfNombreDeLaEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNombreDeLaEmpresaActionPerformed(evt);
            }
        });

        jLabelCif.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabelCif.setText("Cif");

        tfCif.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        tfCif.setForeground(new java.awt.Color(204, 204, 204));
        tfCif.setText("Cif ");
        tfCif.setBorder(null);
        tfCif.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfCifFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfCifFocusLost(evt);
            }
        });

        jLabelAmbito.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabelAmbito.setText("Ambito");

        tfAmbito.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        tfAmbito.setForeground(new java.awt.Color(204, 204, 204));
        tfAmbito.setText("Ambito");
        tfAmbito.setBorder(null);
        tfAmbito.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfAmbitoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfAmbitoFocusLost(evt);
            }
        });

        jLabelTelefono.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabelTelefono.setText("Telefono ");

        tfTelefono.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        tfTelefono.setForeground(new java.awt.Color(204, 204, 204));
        tfTelefono.setText("Telefono");
        tfTelefono.setBorder(null);
        tfTelefono.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfTelefonoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfTelefonoFocusLost(evt);
            }
        });

        jLabelDueño.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabelDueño.setText("Dueño de la empresa");

        tfDueño.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        tfDueño.setForeground(new java.awt.Color(204, 204, 204));
        tfDueño.setText("Dueño ");
        tfDueño.setBorder(null);
        tfDueño.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfDueñoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfDueñoFocusLost(evt);
            }
        });
        tfDueño.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfDueñoActionPerformed(evt);
            }
        });

        jLabelDirección.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabelDirección.setText("Dirección");

        tfDireccion.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        tfDireccion.setForeground(new java.awt.Color(204, 204, 204));
        tfDireccion.setText("Dirección");
        tfDireccion.setBorder(null);
        tfDireccion.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfDireccionFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfDireccionFocusLost(evt);
            }
        });

        jLabelTutor.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabelTutor.setText("Tutor");

        tfTutor.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        tfTutor.setForeground(new java.awt.Color(204, 204, 204));
        tfTutor.setText("Tutor");
        tfTutor.setBorder(null);
        tfTutor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfTutorFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfTutorFocusLost(evt);
            }
        });

        jLabelEmail.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabelEmail.setText("Email");

        tfEmail.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        tfEmail.setForeground(new java.awt.Color(204, 204, 204));
        tfEmail.setText("Email");
        tfEmail.setBorder(null);
        tfEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfEmailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfEmailFocusLost(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel3.setText("Agregar Empresa");

        jPanel5.setBackground(new java.awt.Color(254, 177, 3));
        jPanel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel5MouseExited(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel9.setText("Aceptar");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel9)
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addContainerGap())
        );

        jLabelEmail1.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabelEmail1.setText("Telefóno de contacto");

        tfEmailDeContacto.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        tfEmailDeContacto.setForeground(new java.awt.Color(204, 204, 204));
        tfEmailDeContacto.setText("Email de contacto");
        tfEmailDeContacto.setBorder(null);
        tfEmailDeContacto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfEmailDeContactoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfEmailDeContactoFocusLost(evt);
            }
        });
        tfEmailDeContacto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfEmailDeContactoActionPerformed(evt);
            }
        });

        jLabelNombreDeContacto.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabelNombreDeContacto.setText("Nombre de contacto");

        tfNombreDeContacto.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        tfNombreDeContacto.setForeground(new java.awt.Color(204, 204, 204));
        tfNombreDeContacto.setText("Nombre de contacto");
        tfNombreDeContacto.setBorder(null);
        tfNombreDeContacto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfNombreDeContactoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfNombreDeContactoFocusLost(evt);
            }
        });
        tfNombreDeContacto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNombreDeContactoActionPerformed(evt);
            }
        });

        jLabelEmailDelContacto.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabelEmailDelContacto.setText("Email del contacto");

        tfTelefonoDeContacto1.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        tfTelefonoDeContacto1.setForeground(new java.awt.Color(204, 204, 204));
        tfTelefonoDeContacto1.setText("Telefóno de contacto");
        tfTelefonoDeContacto1.setBorder(null);
        tfTelefonoDeContacto1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfTelefonoDeContacto1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfTelefonoDeContacto1FocusLost(evt);
            }
        });
        tfTelefonoDeContacto1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTelefonoDeContacto1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(142, 142, 142)
                                .addComponent(jLabel3))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(192, 192, 192)
                                .addComponent(jLabel1)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSeparator12, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(9, 9, 9)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tfAmbito, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabelAmbito)
                                            .addComponent(tfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabelEmail))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(9, 9, 9)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(tfTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabelTelefono)))
                                        .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jSeparator11, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(9, 9, 9)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(tfTutor, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabelTutor))))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(9, 9, 9)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tfNombreDeLaEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabelNombre)
                                            .addComponent(tfDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabelDirección))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(9, 9, 9)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(tfCif, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabelCif)))
                                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(9, 9, 9)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(tfDueño, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabelDueño)))
                                        .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelEmailDelContacto)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(tfTelefonoDeContacto1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tfNombreDeContacto, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelEmail1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelNombreDeContacto)
                                .addGap(75, 75, 75))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jSeparator13, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jSeparator14, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(tfEmailDeContacto, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)))))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator16, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelCif)
                        .addGap(18, 18, 18)
                        .addComponent(tfCif, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(jLabelDueño)
                        .addGap(18, 18, 18)
                        .addComponent(tfDueño, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelNombre)
                        .addGap(18, 18, 18)
                        .addComponent(tfNombreDeLaEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(jLabelDirección)
                        .addGap(18, 18, 18)
                        .addComponent(tfDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelAmbito)
                        .addGap(18, 18, 18)
                        .addComponent(tfAmbito, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelEmail)
                        .addGap(18, 18, 18)
                        .addComponent(tfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator12, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelTelefono)
                        .addGap(18, 18, 18)
                        .addComponent(tfTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelTutor)
                        .addGap(18, 18, 18)
                        .addComponent(tfTutor, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator11, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelEmail1)
                    .addComponent(jLabelNombreDeContacto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfNombreDeContacto, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfTelefonoDeContacto1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jSeparator13, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelEmailDelContacto))
                    .addComponent(jSeparator14, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(tfEmailDeContacto, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSeparator16, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tfNombreDeLaEmpresaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfNombreDeLaEmpresaFocusGained
        if (tfNombreDeLaEmpresa.getText().equals("Nombre de la empresa")) {
            tfNombreDeLaEmpresa.setText("");
            tfNombreDeLaEmpresa.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_tfNombreDeLaEmpresaFocusGained

    private void tfNombreDeLaEmpresaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfNombreDeLaEmpresaFocusLost
        if (tfNombreDeLaEmpresa.getText().isEmpty()) {
            tfNombreDeLaEmpresa.setText("Nombre de la empresa");
            tfNombreDeLaEmpresa.setForeground(new Color(204, 204, 204));
        }
    }//GEN-LAST:event_tfNombreDeLaEmpresaFocusLost

    private void tfCifFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfCifFocusGained
        if (tfCif.getText().equals("Cif")) {
            tfCif.setText("");
            tfCif.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_tfCifFocusGained

    private void tfCifFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfCifFocusLost
        if (tfCif.getText().isEmpty()) {
            tfCif.setText("Cif");
            tfCif.setForeground(new Color(204, 204, 204));
        }
    }//GEN-LAST:event_tfCifFocusLost

    private void tfDireccionFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfDireccionFocusGained
        if (tfDireccion.getText().equals("Direccion ")) {
            tfDireccion.setText("");
            tfDireccion.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_tfDireccionFocusGained

    private void tfDireccionFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfDireccionFocusLost
        if (tfDireccion.getText().isEmpty()) {
            tfDireccion.setText("Direccion");
            tfDireccion.setForeground(new Color(204, 204, 204));
        }
    }//GEN-LAST:event_tfDireccionFocusLost

    private void tfDueñoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfDueñoFocusGained
        if (tfDueño.getText().equals("Dueño")) {
            tfDueño.setText("");
            tfDueño.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_tfDueñoFocusGained

    private void tfDueñoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfDueñoFocusLost
        if (tfDueño.getText().isEmpty()) {
            tfDueño.setText("Dueño");
            tfDueño.setForeground(new Color(204, 204, 204));
        }
    }//GEN-LAST:event_tfDueñoFocusLost

    private void tfAmbitoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfAmbitoFocusGained
        if (tfAmbito.getText().equals("Ambito")) {
            tfAmbito.setText("");
            tfAmbito.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_tfAmbitoFocusGained

    private void tfAmbitoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfAmbitoFocusLost
        if (tfAmbito.getText().isEmpty()) {
            tfAmbito.setText("Ambito");
            tfAmbito.setForeground(new Color(204, 204, 204));
        }
    }//GEN-LAST:event_tfAmbitoFocusLost

    private void tfTelefonoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfTelefonoFocusGained
        if (tfTelefono.getText().equals("Telefono")) {
            tfTelefono.setText("");
            tfTelefono.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_tfTelefonoFocusGained

    private void tfTelefonoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfTelefonoFocusLost
        if (tfTelefono.getText().isEmpty()) {
            tfTelefono.setText("Telefono");
            tfTelefono.setForeground(new Color(204, 204, 204));
        }
    }//GEN-LAST:event_tfTelefonoFocusLost

    private void tfEmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfEmailFocusGained
        if (tfEmail.getText().equals("Email")) {
            tfEmail.setText("");
            tfEmail.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_tfEmailFocusGained

    private void tfEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfEmailFocusLost
        if (tfEmail.getText().isEmpty()) {
            tfEmail.setText("Email");
            tfEmail.setForeground(new Color(204, 204, 204));
        }
    }//GEN-LAST:event_tfEmailFocusLost

    private void tfTutorFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfTutorFocusGained
        if (tfTutor.getText().equals("Tutor")) {
            tfTutor.setText("");
            tfTutor.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_tfTutorFocusGained

    private void tfTutorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfTutorFocusLost
        if (tfTutor.getText().isEmpty()) {
            tfTutor.setText("Tutor");
            tfTutor.setForeground(new Color(204, 204, 204));
        }
    }//GEN-LAST:event_tfTutorFocusLost

    private void jPanel5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseEntered
        jPanel5.setBackground(botonSeleccionado);
    }//GEN-LAST:event_jPanel5MouseEntered

    private void jPanel5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseExited
        jPanel5.setBackground(botonNoSeleccionado);
    }//GEN-LAST:event_jPanel5MouseExited

    private void jPanel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseClicked
        MessageDialog message = new MessageDialog(((JFrame) SwingUtilities.getAncestorOfClass(JFrame.class, jPanel1)));
        message.showMessage("Confirmacion de creacion", "¿Esta seguro de querer crear este alumno?");
        
        if (message.getMessageType() == MessageDialog.MessageType.OK) {
            empresaMetodos.comprobarCampos(this,
                tfNombreDeLaEmpresa.getText(), 
                tfCif.getText(), 
                tfDueño.getText(),
                tfDireccion.getText(),
                tfAmbito.getText(), 
                tfTelefono.getText(), 
                tfEmail.getText(),
                tfTutor.getText(),
                tfTelefonoDeContacto1.getText(),
                tfNombreDeContacto.getText(), 
                tfEmailDeContacto.getText());
        }else{
            Notification notificacion = new Notification(((JFrame) SwingUtilities.getAncestorOfClass(JFrame.class, jPanel1)), Notification.Type.INFO, Notification.Location.TOP_CENTER, "¡No se ha creado una empresa!");
            notificacion.showNotification();
        }
        
    }//GEN-LAST:event_jPanel5MouseClicked

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        if (!tfBusqueda.getText().equals("Busque en cualquier campo")) {
            List<Empresa> empresas = empresaMetodos.rellenarListaEmpresa("SELECT * FROM empresa WHERE CAST(id AS TEXT) LIKE '%" + tfBusqueda.getText()
                    + "%' "
                    + "OR nombre LIKE '%" + tfBusqueda.getText() + "%' "
                    + "OR cif LIKE '%" + tfBusqueda.getText() + "%' "
                    + "OR direccion LIKE '%" + tfBusqueda.getText() + "%' "
                    + "OR dueño LIKE '%" + tfBusqueda.getText() + "%' "
                    + "OR ambito LIKE '%" + tfBusqueda.getText() + "%' "
                    + "OR telefono LIKE '%" + tfBusqueda.getText() + "%' "
                    + "OR email LIKE '%" + tfBusqueda.getText() + "%' "        
                    + "OR tutor LIKE '%" + tfBusqueda.getText() + "%' "
                    + "OR telefono_contacto LIKE '%" + tfBusqueda.getText() + "%' "        
                    + "OR nombre_contacto LIKE '%" + tfBusqueda.getText() + "%' "
                    + "OR email_contacto LIKE '%" + tfBusqueda.getText() + "%' ORDER BY id ASC");
            PanelEmpresa.tablaEmpresa = empresaMetodos.rellenarTablaEmpresa(PanelEmpresa.tablaEmpresa, empresas);
        } else {
            List<Empresa> empresas = empresaMetodos.rellenarListaEmpresa("SELECT * FROM empresa where eliminado = FALSE;");
            PanelEmpresa.tablaEmpresa = empresaMetodos.rellenarTablaEmpresa(PanelEmpresa.tablaEmpresa, empresas);
        }
    }//GEN-LAST:event_formWindowClosed

    private void tfNombreDeLaEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNombreDeLaEmpresaActionPerformed
       
    }//GEN-LAST:event_tfNombreDeLaEmpresaActionPerformed

    private void tfDueñoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfDueñoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfDueñoActionPerformed

    private void tfEmailDeContactoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfEmailDeContactoFocusGained
        if (tfEmailDeContacto.getText().equals("Email")) {
            tfEmailDeContacto.setText("");
            tfEmailDeContacto.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_tfEmailDeContactoFocusGained

    private void tfEmailDeContactoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfEmailDeContactoFocusLost
        if (tfEmailDeContacto.getText().equals("Email")) {
            tfEmailDeContacto.setText("");
            tfEmailDeContacto.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_tfEmailDeContactoFocusLost

    private void tfEmailDeContactoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfEmailDeContactoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfEmailDeContactoActionPerformed

    private void tfNombreDeContactoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfNombreDeContactoFocusGained
      if (tfNombreDeContacto.getText().equals("Nombre de contacto")) {
            tfNombreDeContacto.setText("");
            tfNombreDeContacto.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_tfNombreDeContactoFocusGained

    private void tfNombreDeContactoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfNombreDeContactoFocusLost
        if (tfNombreDeContacto.getText().equals("Nombre de contacto")) {
            tfNombreDeContacto.setText("");
            tfNombreDeContacto.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_tfNombreDeContactoFocusLost

    private void tfNombreDeContactoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNombreDeContactoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNombreDeContactoActionPerformed

    private void tfTelefonoDeContacto1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfTelefonoDeContacto1FocusGained
        if (tfTelefonoDeContacto1.getText().equals("Telefóno de contacto")) {
            tfTelefonoDeContacto1.setText("");
            tfTelefonoDeContacto1.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_tfTelefonoDeContacto1FocusGained

    private void tfTelefonoDeContacto1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfTelefonoDeContacto1FocusLost
         if (tfTelefonoDeContacto1.getText().equals("Telefóno de contacto")) {
            tfTelefonoDeContacto1.setText("");
            tfTelefonoDeContacto1.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_tfTelefonoDeContacto1FocusLost

    private void tfTelefonoDeContacto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTelefonoDeContacto1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTelefonoDeContacto1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelAmbito;
    private javax.swing.JLabel jLabelCif;
    private javax.swing.JLabel jLabelDirección;
    private javax.swing.JLabel jLabelDueño;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelEmail1;
    private javax.swing.JLabel jLabelEmailDelContacto;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelNombreDeContacto;
    private javax.swing.JLabel jLabelTelefono;
    private javax.swing.JLabel jLabelTutor;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTextField tfAmbito;
    private javax.swing.JTextField tfCif;
    private javax.swing.JTextField tfDireccion;
    private javax.swing.JTextField tfDueño;
    private javax.swing.JTextField tfEmail;
    private javax.swing.JTextField tfEmailDeContacto;
    private javax.swing.JTextField tfNombreDeContacto;
    private javax.swing.JTextField tfNombreDeLaEmpresa;
    private javax.swing.JTextField tfTelefono;
    private javax.swing.JTextField tfTelefonoDeContacto1;
    private javax.swing.JTextField tfTutor;
    // End of variables declaration//GEN-END:variables
}
