/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package prueba.javaswing;

import java.awt.Color;

/**
 *
 * @author LinkA
 */
public class PanelMenu extends javax.swing.JPanel {

    Color botonSeleccionado = new Color(230, 161, 2);
    Color botonNoSeleccionado = new Color(212,149,2);
    /**
     * Creates new form PanelMenu
     */
    public PanelMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        PanelMenuIzquierda = new javax.swing.JPanel();
        PanelTituloMenuIzquierda = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        PanelBotonmenuIzqAlumnos = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        PanelBotonMenuIzqEmpresas = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        PanelBotonMenuIzqBolsaEmpleo = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        PanelBotonMenuIzqNecesidades = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        PanelBotonMenuIzqUsuarios = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        SeparadorInferiorMenuIzq = new javax.swing.JPanel();
        PanelCentralMenu = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        panelRedondeable7 = new prueba.javaswing.PanelRedondeable();
        jLabel15 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        panelRedondeable1 = new prueba.javaswing.PanelRedondeable();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        panelRedondeable4 = new prueba.javaswing.PanelRedondeable();
        jLabel12 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        panelRedondeable6 = new prueba.javaswing.PanelRedondeable();
        jLabel14 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        panelRedondeable5 = new prueba.javaswing.PanelRedondeable();
        jLabel13 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        PanelMenuIzquierda.setBackground(new java.awt.Color(254, 177, 3));
        PanelMenuIzquierda.setMaximumSize(new java.awt.Dimension(100, 196602));
        PanelMenuIzquierda.setMinimumSize(new java.awt.Dimension(200, 0));
        PanelMenuIzquierda.setLayout(new javax.swing.BoxLayout(PanelMenuIzquierda, javax.swing.BoxLayout.Y_AXIS));

        PanelTituloMenuIzquierda.setBackground(new java.awt.Color(254, 177, 3));
        PanelTituloMenuIzquierda.setMaximumSize(new java.awt.Dimension(250, 10023232));
        PanelTituloMenuIzquierda.setMinimumSize(new java.awt.Dimension(20, 100));
        PanelTituloMenuIzquierda.setLayout(new java.awt.GridBagLayout());

        jLabel6.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel6.setText("Menú principal");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(48, 10, 46, 80);
        PanelTituloMenuIzquierda.add(jLabel6, gridBagConstraints);

        PanelMenuIzquierda.add(PanelTituloMenuIzquierda);

        PanelBotonmenuIzqAlumnos.setBackground(new java.awt.Color(212, 149, 2));
        PanelBotonmenuIzqAlumnos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PanelBotonmenuIzqAlumnos.setMaximumSize(new java.awt.Dimension(250, 10023232));
        PanelBotonmenuIzqAlumnos.setMinimumSize(new java.awt.Dimension(0, 70));
        PanelBotonmenuIzqAlumnos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PanelBotonmenuIzqAlumnosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PanelBotonmenuIzqAlumnosMouseExited(evt);
            }
        });
        PanelBotonmenuIzqAlumnos.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Alumnos");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(32, 88, 24, 94);
        PanelBotonmenuIzqAlumnos.add(jLabel1, gridBagConstraints);

        PanelMenuIzquierda.add(PanelBotonmenuIzqAlumnos);

        PanelBotonMenuIzqEmpresas.setBackground(new java.awt.Color(212, 149, 2));
        PanelBotonMenuIzqEmpresas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PanelBotonMenuIzqEmpresas.setMaximumSize(new java.awt.Dimension(250, 10023232));
        PanelBotonMenuIzqEmpresas.setMinimumSize(new java.awt.Dimension(0, 70));
        PanelBotonMenuIzqEmpresas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PanelBotonMenuIzqEmpresasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PanelBotonMenuIzqEmpresasMouseExited(evt);
            }
        });
        PanelBotonMenuIzqEmpresas.setLayout(new java.awt.GridBagLayout());

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Empresas");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(29, 85, 27, 90);
        PanelBotonMenuIzqEmpresas.add(jLabel7, gridBagConstraints);

        PanelMenuIzquierda.add(PanelBotonMenuIzqEmpresas);

        PanelBotonMenuIzqBolsaEmpleo.setBackground(new java.awt.Color(212, 149, 2));
        PanelBotonMenuIzqBolsaEmpleo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PanelBotonMenuIzqBolsaEmpleo.setMaximumSize(new java.awt.Dimension(250, 10023232));
        PanelBotonMenuIzqBolsaEmpleo.setMinimumSize(new java.awt.Dimension(0, 70));
        PanelBotonMenuIzqBolsaEmpleo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PanelBotonMenuIzqBolsaEmpleoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PanelBotonMenuIzqBolsaEmpleoMouseExited(evt);
            }
        });
        PanelBotonMenuIzqBolsaEmpleo.setLayout(new java.awt.GridBagLayout());

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Bolsa de empleo");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(28, 63, 28, 57);
        PanelBotonMenuIzqBolsaEmpleo.add(jLabel8, gridBagConstraints);

        PanelMenuIzquierda.add(PanelBotonMenuIzqBolsaEmpleo);

        PanelBotonMenuIzqNecesidades.setBackground(new java.awt.Color(212, 149, 2));
        PanelBotonMenuIzqNecesidades.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PanelBotonMenuIzqNecesidades.setMaximumSize(new java.awt.Dimension(250, 10023232));
        PanelBotonMenuIzqNecesidades.setMinimumSize(new java.awt.Dimension(0, 70));
        PanelBotonMenuIzqNecesidades.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PanelBotonMenuIzqNecesidadesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PanelBotonMenuIzqNecesidadesMouseExited(evt);
            }
        });
        PanelBotonMenuIzqNecesidades.setLayout(new java.awt.GridBagLayout());

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Necesidades");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(29, 79, 27, 75);
        PanelBotonMenuIzqNecesidades.add(jLabel9, gridBagConstraints);

        PanelMenuIzquierda.add(PanelBotonMenuIzqNecesidades);

        PanelBotonMenuIzqUsuarios.setBackground(new java.awt.Color(212, 149, 2));
        PanelBotonMenuIzqUsuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PanelBotonMenuIzqUsuarios.setMaximumSize(new java.awt.Dimension(250, 10023232));
        PanelBotonMenuIzqUsuarios.setMinimumSize(new java.awt.Dimension(0, 70));
        PanelBotonMenuIzqUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PanelBotonMenuIzqUsuariosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PanelBotonMenuIzqUsuariosMouseExited(evt);
            }
        });
        PanelBotonMenuIzqUsuarios.setLayout(new java.awt.GridBagLayout());

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("Usuarios");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(29, 93, 27, 90);
        PanelBotonMenuIzqUsuarios.add(jLabel10, gridBagConstraints);

        PanelMenuIzquierda.add(PanelBotonMenuIzqUsuarios);

        SeparadorInferiorMenuIzq.setBackground(new java.awt.Color(254, 177, 3));
        SeparadorInferiorMenuIzq.setMaximumSize(new java.awt.Dimension(250, 10023232));

        javax.swing.GroupLayout SeparadorInferiorMenuIzqLayout = new javax.swing.GroupLayout(SeparadorInferiorMenuIzq);
        SeparadorInferiorMenuIzq.setLayout(SeparadorInferiorMenuIzqLayout);
        SeparadorInferiorMenuIzqLayout.setHorizontalGroup(
            SeparadorInferiorMenuIzqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );
        SeparadorInferiorMenuIzqLayout.setVerticalGroup(
            SeparadorInferiorMenuIzqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 268, Short.MAX_VALUE)
        );

        PanelMenuIzquierda.add(SeparadorInferiorMenuIzq);

        add(PanelMenuIzquierda, java.awt.BorderLayout.LINE_START);

        PanelCentralMenu.setBackground(new java.awt.Color(255, 255, 255));
        PanelCentralMenu.setLayout(new java.awt.GridLayout(3, 3));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        panelRedondeable7.setBackground(new java.awt.Color(254, 177, 3));
        panelRedondeable7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Alumno (Personalizado).png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel2.setText("Alumnos");

        javax.swing.GroupLayout panelRedondeable7Layout = new javax.swing.GroupLayout(panelRedondeable7);
        panelRedondeable7.setLayout(panelRedondeable7Layout);
        panelRedondeable7Layout.setHorizontalGroup(
            panelRedondeable7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRedondeable7Layout.createSequentialGroup()
                .addGroup(panelRedondeable7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRedondeable7Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel15))
                    .addGroup(panelRedondeable7Layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(jLabel2)))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        panelRedondeable7Layout.setVerticalGroup(
            panelRedondeable7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRedondeable7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(panelRedondeable7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(panelRedondeable7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        panelRedondeable7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        PanelCentralMenu.add(jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 337, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 271, Short.MAX_VALUE)
        );

        PanelCentralMenu.add(jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        panelRedondeable1.setBackground(new java.awt.Color(254, 177, 3));
        panelRedondeable1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Empresa (Personalizado).png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel3.setText("Empresas");

        javax.swing.GroupLayout panelRedondeable1Layout = new javax.swing.GroupLayout(panelRedondeable1);
        panelRedondeable1.setLayout(panelRedondeable1Layout);
        panelRedondeable1Layout.setHorizontalGroup(
            panelRedondeable1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRedondeable1Layout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addGroup(panelRedondeable1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRedondeable1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(37, 37, 37))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRedondeable1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(69, 69, 69))))
        );
        panelRedondeable1Layout.setVerticalGroup(
            panelRedondeable1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRedondeable1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(panelRedondeable1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(panelRedondeable1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        panelRedondeable1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        PanelCentralMenu.add(jPanel3);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 337, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 271, Short.MAX_VALUE)
        );

        PanelCentralMenu.add(jPanel4);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        panelRedondeable4.setBackground(new java.awt.Color(254, 177, 3));
        panelRedondeable4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/profile_img (Personalizado).png"))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel5.setText("Usuarios");

        javax.swing.GroupLayout panelRedondeable4Layout = new javax.swing.GroupLayout(panelRedondeable4);
        panelRedondeable4.setLayout(panelRedondeable4Layout);
        panelRedondeable4Layout.setHorizontalGroup(
            panelRedondeable4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRedondeable4Layout.createSequentialGroup()
                .addGroup(panelRedondeable4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRedondeable4Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel12))
                    .addGroup(panelRedondeable4Layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jLabel5)))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        panelRedondeable4Layout.setVerticalGroup(
            panelRedondeable4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRedondeable4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(panelRedondeable4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(panelRedondeable4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        panelRedondeable4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        PanelCentralMenu.add(jPanel5);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 337, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 271, Short.MAX_VALUE)
        );

        PanelCentralMenu.add(jPanel6);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        panelRedondeable6.setBackground(new java.awt.Color(254, 177, 3));
        panelRedondeable6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/BolsaEmpleo (Personalizado).png"))); // NOI18N

        jLabel11.setText("Usuarios");

        jLabel16.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel16.setText("Bolsa de empleo");

        javax.swing.GroupLayout panelRedondeable6Layout = new javax.swing.GroupLayout(panelRedondeable6);
        panelRedondeable6.setLayout(panelRedondeable6Layout);
        panelRedondeable6Layout.setHorizontalGroup(
            panelRedondeable6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRedondeable6Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(panelRedondeable6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRedondeable6Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel16))
                    .addComponent(jLabel14))
                .addContainerGap(42, Short.MAX_VALUE))
            .addGroup(panelRedondeable6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelRedondeable6Layout.createSequentialGroup()
                    .addGap(92, 92, 92)
                    .addComponent(jLabel11)
                    .addContainerGap(93, Short.MAX_VALUE)))
        );
        panelRedondeable6Layout.setVerticalGroup(
            panelRedondeable6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRedondeable6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16)
                .addContainerGap(16, Short.MAX_VALUE))
            .addGroup(panelRedondeable6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelRedondeable6Layout.createSequentialGroup()
                    .addGap(93, 93, 93)
                    .addComponent(jLabel11)
                    .addContainerGap(93, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(panelRedondeable6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(panelRedondeable6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        panelRedondeable6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        PanelCentralMenu.add(jPanel7);

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 337, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 271, Short.MAX_VALUE)
        );

        PanelCentralMenu.add(jPanel8);

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));

        panelRedondeable5.setBackground(new java.awt.Color(254, 177, 3));
        panelRedondeable5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Necesidades (Personalizado).png"))); // NOI18N

        jLabel17.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel17.setText("Necesidades");

        javax.swing.GroupLayout panelRedondeable5Layout = new javax.swing.GroupLayout(panelRedondeable5);
        panelRedondeable5.setLayout(panelRedondeable5Layout);
        panelRedondeable5Layout.setHorizontalGroup(
            panelRedondeable5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRedondeable5Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel13)
                .addContainerGap(38, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRedondeable5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel17)
                .addGap(59, 59, 59))
        );
        panelRedondeable5Layout.setVerticalGroup(
            panelRedondeable5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRedondeable5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(jLabel17)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(panelRedondeable5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(panelRedondeable5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        panelRedondeable5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        PanelCentralMenu.add(jPanel9);

        add(PanelCentralMenu, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PanelLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PanelLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PanelLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PanelLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PanelMenu().setVisible(true);
            }
        });
    }
    
    private void PanelBotonmenuIzqAlumnosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelBotonmenuIzqAlumnosMouseEntered
        PanelBotonmenuIzqAlumnos.setBackground(botonSeleccionado);
    }//GEN-LAST:event_PanelBotonmenuIzqAlumnosMouseEntered

    private void PanelBotonmenuIzqAlumnosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelBotonmenuIzqAlumnosMouseExited
        PanelBotonmenuIzqAlumnos.setBackground(botonNoSeleccionado);
    }//GEN-LAST:event_PanelBotonmenuIzqAlumnosMouseExited

    private void PanelBotonMenuIzqEmpresasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelBotonMenuIzqEmpresasMouseEntered
        PanelBotonMenuIzqEmpresas.setBackground(botonSeleccionado);
    }//GEN-LAST:event_PanelBotonMenuIzqEmpresasMouseEntered

    private void PanelBotonMenuIzqEmpresasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelBotonMenuIzqEmpresasMouseExited
        PanelBotonMenuIzqEmpresas.setBackground(botonNoSeleccionado);
    }//GEN-LAST:event_PanelBotonMenuIzqEmpresasMouseExited

    private void PanelBotonMenuIzqBolsaEmpleoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelBotonMenuIzqBolsaEmpleoMouseEntered
        PanelBotonMenuIzqBolsaEmpleo.setBackground(botonSeleccionado);
    }//GEN-LAST:event_PanelBotonMenuIzqBolsaEmpleoMouseEntered

    private void PanelBotonMenuIzqBolsaEmpleoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelBotonMenuIzqBolsaEmpleoMouseExited
        PanelBotonMenuIzqBolsaEmpleo.setBackground(botonNoSeleccionado);
    }//GEN-LAST:event_PanelBotonMenuIzqBolsaEmpleoMouseExited

    private void PanelBotonMenuIzqNecesidadesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelBotonMenuIzqNecesidadesMouseEntered
        PanelBotonMenuIzqNecesidades.setBackground(botonSeleccionado);
    }//GEN-LAST:event_PanelBotonMenuIzqNecesidadesMouseEntered

    private void PanelBotonMenuIzqNecesidadesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelBotonMenuIzqNecesidadesMouseExited
        PanelBotonMenuIzqNecesidades.setBackground(botonNoSeleccionado);
    }//GEN-LAST:event_PanelBotonMenuIzqNecesidadesMouseExited

    private void PanelBotonMenuIzqUsuariosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelBotonMenuIzqUsuariosMouseEntered
        PanelBotonMenuIzqUsuarios.setBackground(botonSeleccionado);
    }//GEN-LAST:event_PanelBotonMenuIzqUsuariosMouseEntered

    private void PanelBotonMenuIzqUsuariosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelBotonMenuIzqUsuariosMouseExited
        PanelBotonMenuIzqUsuarios.setBackground(botonNoSeleccionado);
    }//GEN-LAST:event_PanelBotonMenuIzqUsuariosMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelBotonMenuIzqBolsaEmpleo;
    private javax.swing.JPanel PanelBotonMenuIzqEmpresas;
    private javax.swing.JPanel PanelBotonMenuIzqNecesidades;
    private javax.swing.JPanel PanelBotonMenuIzqUsuarios;
    private javax.swing.JPanel PanelBotonmenuIzqAlumnos;
    private javax.swing.JPanel PanelCentralMenu;
    private javax.swing.JPanel PanelMenuIzquierda;
    private javax.swing.JPanel PanelTituloMenuIzquierda;
    private javax.swing.JPanel SeparadorInferiorMenuIzq;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private prueba.javaswing.PanelRedondeable panelRedondeable1;
    private prueba.javaswing.PanelRedondeable panelRedondeable4;
    private prueba.javaswing.PanelRedondeable panelRedondeable5;
    private prueba.javaswing.PanelRedondeable panelRedondeable6;
    private prueba.javaswing.PanelRedondeable panelRedondeable7;
    // End of variables declaration//GEN-END:variables
}
